In [1]:
from torch import nn
import pandas as pd
import matplotlib as plt

In [2]:
df = pd.read_csv('../../data/data_regression.csv')

In [3]:
df.head()

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,2015,100198,409-8743,Female,36,62,no,no,148.35,12.2,16.81,82,1,4.0,1,0.0
1,2015,100643,340-5930,Female,39,149,no,no,294.45,7.7,33.37,87,3,3.0,2,0.0
2,2015,100756,372-3750,Female,65,126,no,no,87.30,11.9,9.89,91,1,4.0,5,1.0
3,2015,101595,331-4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0
4,2015,101653,351-8398,Female,40,191,no,no,243.00,10.9,27.54,83,7,3.0,1,0.0

In [4]:
data = df.drop(['customer_id', 'phone_no', 'year'], axis=1)

In [5]:
data.tail()

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
1995,Female,54,75,no,yes,182.25,11.3,20.66,97,5,4.0,2,NaN
1996,Male,45,127,no,no,273.45,9.3,30.99,116,3,3.0,1,0.0
1997,NaN,53,94,no,no,128.85,15.6,14.60,110,16,5.0,0,0.0
1998,Male,40,94,no,no,178.05,10.4,20.18,100,6,NaN,3,0.0
1999,Male,37,73,no,no,326.70,10.3,37.03,89,6,3.0,1,1.0

In [6]:
data.describe()

,age,no_of_days_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
count,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,1972.000000,2000.000000,1965.000000
mean,38.69050,99.750000,270.178425,10.198700,30.620780,100.415500,4.482500,3.250507,1.547000,0.133333
std,10.20641,39.755386,80.551627,2.785519,9.129165,19.529454,2.487728,0.809084,1.315164,0.340021
min,18.00000,1.000000,0.000000,0.000000,0.000000,42.000000,0.000000,0.000000,0.000000,0.000000
25%,32.00000,73.000000,218.212500,8.400000,24.735000,87.000000,3.000000,3.000000,1.000000,0.000000
50%,37.00000,99.000000,269.925000,10.200000,30.590000,101.000000,4.000000,3.000000,1.000000,0.000000
75%,44.00000,127.000000,324.675000,12.000000,36.797500,114.000000,6.000000,4.000000,2.000000,0.000000
max,82.00000,243.000000,526.200000,20.000000,59.640000,175.000000,19.000000,6.000000,9.000000,1.000000

### Droping Null Values

In [7]:
data.isna().sum()

gender                    24
age                        0
no_of_days_subscribed      0
multi_screen               0
mail_subscribed            0
weekly_mins_watched        0
minimum_daily_mins         0
maximum_daily_mins         0
weekly_max_night_mins      0
videos_watched             0
maximum_days_inactive     28
customer_support_calls     0
churn                     35
dtype: int64

In [8]:
data.shape

(2000, 13)

In [9]:
data = data.dropna(axis=0)

In [10]:
data.isna().sum()

gender                    0
age                       0
no_of_days_subscribed     0
multi_screen              0
mail_subscribed           0
weekly_mins_watched       0
minimum_daily_mins        0
maximum_daily_mins        0
weekly_max_night_mins     0
videos_watched            0
maximum_days_inactive     0
customer_support_calls    0
churn                     0
dtype: int64

In [11]:
data.shape

(1918, 13)

#### Categorical Variables

In [12]:
data['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [13]:
print(data['multi_screen'].unique())
print(data['mail_subscribed'].unique())

['no' 'yes']
['no' 'yes']

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [15]:
data['gender'] = le.fit_transform(data['gender'])
data['multi_screen'] = le.fit_transform(data['multi_screen'])
data['mail_subscribed'] = le.fit_transform(data['mail_subscribed'])

In [16]:
data.head()

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,0,36,62,0,0,148.35,12.2,16.81,82,1,4.0,1,0.0
1,0,39,149,0,0,294.45,7.7,33.37,87,3,3.0,2,0.0
2,0,65,126,0,0,87.30,11.9,9.89,91,1,4.0,5,1.0
3,0,24,131,0,1,321.30,9.5,36.41,102,4,3.0,3,0.0
4,0,40,191,0,0,243.00,10.9,27.54,83,7,3.0,1,0.0

In [17]:
data.groupby('churn').size()

churn
0.0    1665
1.0     253
dtype: int64

### Numerical

In [18]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [19]:
data_num = data.drop(['gender', 'multi_screen', 'mail_subscribed'], axis = 1)

In [20]:
cols = data_num.columns
data_num = scaler.fit_transform(data_num)

In [21]:
cols = list(cols)

In [22]:
data[cols] = data_num

In [23]:
data.head()

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,0,0.281250,0.252066,0,0,0.281927,0.610,0.281858,0.300752,0.052632,0.666667,0.111111,0.0
1,0,0.328125,0.611570,0,0,0.559578,0.385,0.559524,0.338346,0.157895,0.500000,0.222222,0.0
2,0,0.734375,0.516529,0,0,0.165906,0.595,0.165828,0.368421,0.052632,0.666667,0.555556,1.0
3,0,0.093750,0.537190,0,1,0.610604,0.475,0.610496,0.451128,0.210526,0.500000,0.333333,0.0
4,0,0.343750,0.785124,0,0,0.461802,0.545,0.461771,0.308271,0.368421,0.500000,0.111111,0.0

In [24]:
X = data.drop('churn', axis = 1)
y = data['churn'].astype(int)

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X.values, y, test_size=0.2, random_state=42)

### Sequential Neural Network

In [26]:
X_test.shape

(384, 12)

In [27]:
#Hyperparameters for our network
input_size = X.shape[1]
hidden_sizes = [128, 64]
output_size = 2

In [28]:
import torch

model = nn.Sequential(nn.Linear(input_size, hidden_sizes[0]),
                      nn.ReLU(),
                      nn.Linear(hidden_sizes[0], hidden_sizes[1]),
                      nn.ReLU(),
                      nn.Linear(hidden_sizes[1], output_size),
                      nn.Softmax(dim=1))

In [29]:
print(model)

Sequential(
  (0): Linear(in_features=12, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=2, bias=True)
  (5): Softmax(dim=1)
)

In [30]:
from collections import OrderedDict

model_dict = nn.Sequential(OrderedDict([
    ('fc1', nn.Linear(input_size, hidden_sizes[0])),
    ('relu1', nn.ReLU()),
    ('fc2', nn.Linear(hidden_sizes[0], hidden_sizes[1])),
    ('relu2', nn.ReLU()),
    ('output', nn.Linear(hidden_sizes[1], output_size)),
    ('softmax', nn.Softmax(dim=1))
]))

In [31]:
#define the loss
criterion = nn.NLLLoss()

In [32]:
from torch import optim

optimizer = optim.SGD(model.parameters(), lr=0.01)

In [33]:
import torch.utils.data as Data
from torch import Tensor
import numpy as np

In [34]:
X_train = Tensor(X_train)
y_train = Tensor(np.array(y_train))

In [35]:
BATCH_SIZE = 64

torch_dataset = Data.TensorDataset(X_train, y_train)

loder = Data.DataLoader(
    dataset=torch_dataset,
    batch_size = BATCH_SIZE,
    shuffle=True, num_workers=2,
)

### Training the model

In [36]:
from torch.autograd import Variable

epochs = 100

for e in range(epochs):
    running_loss = 0
    for step, (batch_x, batch_y) in enumerate(loder):
        #print(f'b_x shape: {b_x.shape}')  # Add this debug line temporarily
        b_x = Variable(batch_x)
        b_y = Variable(batch_y.type(torch.LongTensor))

        optimizer.zero_grad()

        output = model(b_x)
        loss = criterion(output, b_y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    else:
        print(f'Training loss: {running_loss/len(X_train)}')

Training loss: -0.00797295006965876
Training loss: -0.008763704570362435
Training loss: -0.00958640657783021
Training loss: -0.01040505138960469
Training loss: -0.011150144574850447
Training loss: -0.011760088541050777
Training loss: -0.012218038409443225
Training loss: -0.012550335081180041
Training loss: -0.012784957030916774
Training loss: -0.012950553266134847
Training loss: -0.013071919940752031
Training loss: -0.013161949220816501
Training loss: -0.013230631217807338
Training loss: -0.013284380269641205
Training loss: -0.013325147787315438
Training loss: -0.013361442974990785
Training loss: -0.013388379417466682
Training loss: -0.013411533879176889
Training loss: -0.013430886737992587
Training loss: -0.013446735784003445
Training loss: -0.013460517007337866
Training loss: -0.01347272177718609
Training loss: -0.013484304816968438
Training loss: -0.013494591280876269
Training loss: -0.013503485817020223
Training loss: -0.013508852061267937
Training loss: -0.013516033488426556
Training loss: -0.01352123529534918
Training loss: -0.013528795682156102
Training loss: -0.013530654189173215
Training loss: -0.013535985735280262
Training loss: -0.013539619947816434
Training loss: -0.013543895551403002
Training loss: -0.01354820799019377
Training loss: -0.013551600170570681
Training loss: -0.013554456414268723
Training loss: -0.013555772845406265
Training loss: -0.013559826660653604
Training loss: -0.013560788611234244
Training loss: -0.013562587513606582
Training loss: -0.013563575380939549
Training loss: -0.013567381180249728
Training loss: -0.013568122197316554
Training loss: -0.01357008468218857
Training loss: -0.013571607670230692
Training loss: -0.013573384774554973
Training loss: -0.013575383550651382
Training loss: -0.01357471616513726
Training loss: -0.013576257648492886
Training loss: -0.013576746919475292
Training loss: -0.013579144899040033
Training loss: -0.013579861980995268
Training loss: -0.013579210526318407
Training loss: -0.013582424708730705
Training loss: -0.013583330163122622
Training loss: -0.013584828205804938
Training loss: -0.013583366260068513
Training loss: -0.013586099292339837
Training loss: -0.01358618687308907
Training loss: -0.013584612206965102
Training loss: -0.013586929832940929
Training loss: -0.01358856826126964
Training loss: -0.013588213003598727
Training loss: -0.013588813751586257
Training loss: -0.01359069545545665
Training loss: -0.01359059637342003
Training loss: -0.0135911445496446
Training loss: -0.013591651616537897
Training loss: -0.013591488694585131
Training loss: -0.013593281885169476
Training loss: -0.013593409992414473
Training loss: -0.013592217899518965
Training loss: -0.013592651762272263
Training loss: -0.013594367863146547
Training loss: -0.013595425554173556
Training loss: -0.01359548993806951
Training loss: -0.01359651654453601
Training loss: -0.013594584639100394
Training loss: -0.013597891103801702
Training loss: -0.013596592934843459
Training loss: -0.013595608797657754
Training loss: -0.013596261845418341
Training loss: -0.013596903391891539
Training loss: -0.013599169417496922
Training loss: -0.013596507530013461
Training loss: -0.013598106364383225
Training loss: -0.013598382783837548
Training loss: -0.01359733733235624
Training loss: -0.013597925296818261
Training loss: -0.013598836424142472
Training loss: -0.013599409312592648
Training loss: -0.013598011401050871
Training loss: -0.013599227584480773
Training loss: -0.013598801609434703
Training loss: -0.013600009633167471
Training loss: -0.013600221163601732
Training loss: -0.013600437473287172
Training loss: -0.013601297000240938
Training loss: -0.013601496019139594
Training loss: -0.01360202375726563

In [37]:
X_test = Tensor(X_test)
y_test = Tensor(np.array(y_test))
z = model(X_test)

In [38]:
z

tensor([[9.9618e-01, 3.8248e-03],
        [9.9814e-01, 1.8576e-03],
        [9.9902e-01, 9.8151e-04],
        [9.9846e-01, 1.5360e-03],
        [9.9900e-01, 1.0016e-03],
        [9.9970e-01, 3.0342e-04],
        [9.9867e-01, 1.3264e-03],
        [9.9975e-01, 2.5005e-04],
        [9.9886e-01, 1.1426e-03],
        [9.9887e-01, 1.1274e-03],
        [9.9793e-01, 2.0724e-03],
        [9.9879e-01, 1.2146e-03],
        [9.9921e-01, 7.9378e-04],
        [9.9853e-01, 1.4666e-03],
        [9.9899e-01, 1.0124e-03],
        [9.9938e-01, 6.2485e-04],
        [9.9891e-01, 1.0877e-03],
        [9.9967e-01, 3.2958e-04],
        [9.9907e-01, 9.2962e-04],
        [9.9959e-01, 4.0793e-04],
        [9.9976e-01, 2.3846e-04],
        [9.9923e-01, 7.6758e-04],
        [9.9950e-01, 4.9897e-04],
        [9.9747e-01, 2.5319e-03],
        [9.9965e-01, 3.5182e-04],
        [9.9941e-01, 5.8572e-04],
        [9.9726e-01, 2.7430e-03],
        [9.9956e-01, 4.3658e-04],
        [9.9887e-01, 1.1263e-03],
        [9.9921e-01, 7.8529e-04],
        [9.9903e-01, 9.6750e-04],
        [9.9927e-01, 7.2822e-04],
        [9.9942e-01, 5.7948e-04],
        [9.9887e-01, 1.1261e-03],
        [9.9975e-01, 2.4636e-04],
        [9.9965e-01, 3.4841e-04],
        [9.9790e-01, 2.0964e-03],
        [9.9972e-01, 2.8430e-04],
        [9.9898e-01, 1.0179e-03],
        [9.9955e-01, 4.5167e-04],
        [9.9974e-01, 2.6183e-04],
        [9.9677e-01, 3.2252e-03],
        [9.9930e-01, 7.0182e-04],
        [9.9827e-01, 1.7267e-03],
        [9.9794e-01, 2.0586e-03],
        [9.9939e-01, 6.0627e-04],
        [9.9926e-01, 7.4033e-04],
        [9.9923e-01, 7.7212e-04],
        [9.9981e-01, 1.8702e-04],
        [9.9650e-01, 3.5015e-03],
        [9.9917e-01, 8.2846e-04],
        [9.9862e-01, 1.3800e-03],
        [9.9941e-01, 5.9041e-04],
        [9.9605e-01, 3.9536e-03],
        [9.9949e-01, 5.1123e-04],
        [9.9922e-01, 7.8056e-04],
        [9.9934e-01, 6.5764e-04],
        [9.9946e-01, 5.4008e-04],
        [9.9848e-01, 1.5167e-03],
        [9.9735e-01, 2.6495e-03],
        [9.9943e-01, 5.7322e-04],
        [9.9902e-01, 9.8180e-04],
        [9.9882e-01, 1.1849e-03],
        [9.9847e-01, 1.5285e-03],
        [9.9944e-01, 5.5741e-04],
        [9.9963e-01, 3.7160e-04],
        [9.9865e-01, 1.3474e-03],
        [9.9808e-01, 1.9177e-03],
        [9.9671e-01, 3.2891e-03],
        [9.9893e-01, 1.0736e-03],
        [9.9978e-01, 2.2355e-04],
        [9.9877e-01, 1.2325e-03],
        [9.9888e-01, 1.1159e-03],
        [9.9958e-01, 4.1875e-04],
        [9.9915e-01, 8.5115e-04],
        [9.9907e-01, 9.3193e-04],
        [9.9927e-01, 7.2859e-04],
        [9.9758e-01, 2.4229e-03],
        [9.9888e-01, 1.1185e-03],
        [9.9841e-01, 1.5919e-03],
        [9.9911e-01, 8.9391e-04],
        [9.9855e-01, 1.4485e-03],
        [9.9740e-01, 2.6017e-03],
        [9.9964e-01, 3.6232e-04],
        [9.9935e-01, 6.5409e-04],
        [9.9843e-01, 1.5678e-03],
        [9.9766e-01, 2.3390e-03],
        [9.9836e-01, 1.6418e-03],
        [9.9905e-01, 9.4987e-04],
        [9.9977e-01, 2.2651e-04],
        [9.9899e-01, 1.0085e-03],
        [9.9980e-01, 1.9881e-04],
        [9.9931e-01, 6.8952e-04],
        [9.9519e-01, 4.8097e-03],
        [9.9647e-01, 3.5349e-03],
        [9.9924e-01, 7.5824e-04],
        [9.9852e-01, 1.4771e-03],
        [9.9921e-01, 7.8682e-04],
        [9.9985e-01, 1.5444e-04],
        [9.9628e-01, 3.7162e-03],
        [9.9918e-01, 8.2446e-04],
        [9.9931e-01, 6.8784e-04],
        [9.9936e-01, 6.3852e-04],
        [9.9934e-01, 6.6242e-04],
        [9.9976e-01, 2.3834e-04],
        [9.9955e-01, 4.4862e-04],
        [9.9969e-01, 3.0669e-04],
        [9.9773e-01, 2.2745e-03],
        [9.9943e-01, 5.7005e-04],
        [9.9868e-01, 1.3193e-03],
        [9.9903e-01, 9.7476e-04],
        [9.9891e-01, 1.0865e-03],
        [9.9973e-01, 2.7177e-04],
        [9.9919e-01, 8.0935e-04],
        [9.9948e-01, 5.2026e-04],
        [9.9848e-01, 1.5182e-03],
        [9.9960e-01, 3.9987e-04],
        [9.9949e-01, 5.1386e-04],
        [9.9769e-01, 2.3062e-03],
        [9.9795e-01, 2.0498e-03],
        [9.9699e-01, 3.0123e-03],
        [9.9490e-01, 5.0996e-03],
        [9.9889e-01, 1.1079e-03],
        [9.9970e-01, 3.0186e-04],
        [9.9851e-01, 1.4890e-03],
        [9.9912e-01, 8.8119e-04],
        [9.9862e-01, 1.3807e-03],
        [9.9868e-01, 1.3240e-03],
        [9.9722e-01, 2.7781e-03],
        [9.9884e-01, 1.1618e-03],
        [9.9841e-01, 1.5905e-03],
        [9.9858e-01, 1.4243e-03],
        [9.9824e-01, 1.7607e-03],
        [9.9960e-01, 4.0201e-04],
        [9.9870e-01, 1.3047e-03],
        [9.9819e-01, 1.8067e-03],
        [9.9804e-01, 1.9636e-03],
        [9.9828e-01, 1.7213e-03],
        [9.9979e-01, 2.1421e-04],
        [9.9904e-01, 9.6103e-04],
        [9.9843e-01, 1.5727e-03],
        [9.9905e-01, 9.5209e-04],
        [9.9920e-01, 8.0188e-04],
        [9.9917e-01, 8.2608e-04],
        [9.9932e-01, 6.7808e-04],
        [9.9905e-01, 9.5283e-04],
        [9.9961e-01, 3.9347e-04],
        [9.9694e-01, 3.0622e-03],
        [9.9923e-01, 7.6639e-04],
        [9.9889e-01, 1.1124e-03],
        [9.9845e-01, 1.5544e-03],
        [9.9939e-01, 6.1480e-04],
        [9.9894e-01, 1.0558e-03],
        [9.9802e-01, 1.9800e-03],
        [9.9757e-01, 2.4321e-03],
        [9.9797e-01, 2.0269e-03],
        [9.9881e-01, 1.1858e-03],
        [9.9590e-01, 4.1017e-03],
        [9.9941e-01, 5.8880e-04],
        [9.9945e-01, 5.4973e-04],
        [9.9887e-01, 1.1331e-03],
        [9.9978e-01, 2.1785e-04],
        [9.9945e-01, 5.4652e-04],
        [9.9920e-01, 8.0329e-04],
        [9.9829e-01, 1.7074e-03],
        [9.9936e-01, 6.3844e-04],
        [9.9850e-01, 1.4950e-03],
        [9.9934e-01, 6.5793e-04],
        [9.9835e-01, 1.6489e-03],
        [9.9934e-01, 6.6070e-04],
        [9.9968e-01, 3.2154e-04],
        [9.9886e-01, 1.1377e-03],
        [9.9887e-01, 1.1347e-03],
        [9.9947e-01, 5.3131e-04],
        [9.9965e-01, 3.5051e-04],
        [9.9887e-01, 1.1255e-03],
        [9.9943e-01, 5.7081e-04],
        [9.9809e-01, 1.9146e-03],
        [9.9920e-01, 8.0086e-04],
        [9.9935e-01, 6.5017e-04],
        [9.9840e-01, 1.6012e-03],
        [9.9916e-01, 8.4146e-04],
        [9.9963e-01, 3.7041e-04],
        [9.9947e-01, 5.3346e-04],
        [9.9868e-01, 1.3217e-03],
        [9.9947e-01, 5.2771e-04],
        [9.9817e-01, 1.8287e-03],
        [9.9816e-01, 1.8412e-03],
        [9.9970e-01, 3.0471e-04],
        [9.9949e-01, 5.0684e-04],
        [9.9767e-01, 2.3322e-03],
        [9.9972e-01, 2.7534e-04],
        [9.9917e-01, 8.3378e-04],
        [9.9964e-01, 3.6176e-04],
        [9.9765e-01, 2.3472e-03],
        [9.9937e-01, 6.3246e-04],
        [9.9918e-01, 8.1655e-04],
        [9.9974e-01, 2.5888e-04],
        [9.9922e-01, 7.7950e-04],
        [9.9925e-01, 7.5415e-04],
        [9.9920e-01, 8.0150e-04],
        [9.9968e-01, 3.2431e-04],
        [9.9916e-01, 8.3536e-04],
        [9.9882e-01, 1.1794e-03],
        [9.9969e-01, 3.0654e-04],
        [9.9947e-01, 5.2620e-04],
        [9.9808e-01, 1.9245e-03],
        [9.9923e-01, 7.6643e-04],
        [9.9874e-01, 1.2599e-03],
        [9.9954e-01, 4.6270e-04],
        [9.9957e-01, 4.2908e-04],
        [9.9976e-01, 2.4449e-04],
        [9.9953e-01, 4.7350e-04],
        [9.9972e-01, 2.7919e-04],
        [9.9947e-01, 5.3175e-04],
        [9.9867e-01, 1.3329e-03],
        [9.9918e-01, 8.1552e-04],
        [9.9898e-01, 1.0234e-03],
        [9.9837e-01, 1.6299e-03],
        [9.9937e-01, 6.2656e-04],
        [9.9929e-01, 7.1486e-04],
        [9.9913e-01, 8.7045e-04],
        [9.9949e-01, 5.1427e-04],
        [9.9940e-01, 6.0289e-04],
        [9.9898e-01, 1.0232e-03],
        [9.9974e-01, 2.5622e-04],
        [9.9822e-01, 1.7782e-03],
        [9.9963e-01, 3.7132e-04],
        [9.9938e-01, 6.1881e-04],
        [9.9961e-01, 3.9057e-04],
        [9.9835e-01, 1.6509e-03],
        [9.9807e-01, 1.9331e-03],
        [9.9929e-01, 7.1078e-04],
        [9.9686e-01, 3.1354e-03],
        [9.9939e-01, 6.0905e-04],
        [9.9938e-01, 6.2000e-04],
        [9.9882e-01, 1.1792e-03],
        [9.9923e-01, 7.6923e-04],
        [9.9950e-01, 4.9872e-04],
        [9.9952e-01, 4.8233e-04],
        [9.9958e-01, 4.2492e-04],
        [9.9901e-01, 9.9009e-04],
        [9.9958e-01, 4.2124e-04],
        [9.9914e-01, 8.6222e-04],
        [9.9914e-01, 8.6143e-04],
        [9.9882e-01, 1.1807e-03],
        [9.9921e-01, 7.8918e-04],
        [9.9688e-01, 3.1203e-03],
        [9.9711e-01, 2.8864e-03],
        [9.9925e-01, 7.4513e-04],
        [9.9860e-01, 1.3989e-03],
        [9.9824e-01, 1.7627e-03],
        [9.9958e-01, 4.1612e-04],
        [9.9941e-01, 5.9095e-04],
        [9.9971e-01, 2.8662e-04],
        [9.9936e-01, 6.4131e-04],
        [9.9804e-01, 1.9621e-03],
        [9.9883e-01, 1.1652e-03],
        [9.9981e-01, 1.9036e-04],
        [9.9946e-01, 5.4293e-04],
        [9.9714e-01, 2.8641e-03],
        [9.9935e-01, 6.4515e-04],
        [9.9872e-01, 1.2771e-03],
        [9.9930e-01, 6.9666e-04],
        [9.9968e-01, 3.1982e-04],
        [9.9731e-01, 2.6864e-03],
        [9.9751e-01, 2.4892e-03],
        [9.9932e-01, 6.8322e-04],
        [9.9886e-01, 1.1424e-03],
        [9.9953e-01, 4.7036e-04],
        [9.9722e-01, 2.7752e-03],
        [9.9783e-01, 2.1721e-03],
        [9.9903e-01, 9.7450e-04],
        [9.9865e-01, 1.3516e-03],
        [9.9969e-01, 3.0709e-04],
        [9.9921e-01, 7.8651e-04],
        [9.9726e-01, 2.7358e-03],
        [9.9959e-01, 4.0621e-04],
        [9.9582e-01, 4.1843e-03],
        [9.9868e-01, 1.3199e-03],
        [9.9930e-01, 6.9543e-04],
        [9.9949e-01, 5.0993e-04],
        [9.9682e-01, 3.1829e-03],
        [9.9844e-01, 1.5644e-03],
        [9.9909e-01, 9.0712e-04],
        [9.9961e-01, 3.8691e-04],
        [9.9906e-01, 9.4333e-04],
        [9.9959e-01, 4.0970e-04],
        [9.9874e-01, 1.2556e-03],
        [9.9888e-01, 1.1161e-03],
        [9.9897e-01, 1.0304e-03],
        [9.9939e-01, 6.0700e-04],
        [9.9937e-01, 6.2723e-04],
        [9.9931e-01, 6.9158e-04],
        [9.9828e-01, 1.7176e-03],
        [9.9979e-01, 2.1088e-04],
        [9.9923e-01, 7.7295e-04],
        [9.9774e-01, 2.2579e-03],
        [9.9971e-01, 2.8953e-04],
        [9.9952e-01, 4.8120e-04],
        [9.9931e-01, 6.9100e-04],
        [9.9948e-01, 5.1556e-04],
        [9.9771e-01, 2.2905e-03],
        [9.9962e-01, 3.7663e-04],
        [9.9945e-01, 5.5046e-04],
        [9.9648e-01, 3.5210e-03],
        [9.9929e-01, 7.1250e-04],
        [9.9978e-01, 2.2287e-04],
        [9.9737e-01, 2.6273e-03],
        [9.9973e-01, 2.7183e-04],
        [9.9964e-01, 3.6414e-04],
        [9.9898e-01, 1.0231e-03],
        [9.9915e-01, 8.5120e-04],
        [9.9966e-01, 3.4344e-04],
        [9.9940e-01, 6.0180e-04],
        [9.9975e-01, 2.5367e-04],
        [9.9984e-01, 1.5834e-04],
        [9.9875e-01, 1.2516e-03],
        [9.9887e-01, 1.1273e-03],
        [9.9935e-01, 6.4850e-04],
        [9.9892e-01, 1.0813e-03],
        [9.9893e-01, 1.0698e-03],
        [9.9836e-01, 1.6356e-03],
        [9.9882e-01, 1.1783e-03],
        [9.9932e-01, 6.7522e-04],
        [9.9844e-01, 1.5565e-03],
        [9.9910e-01, 9.0240e-04],
        [9.9562e-01, 4.3807e-03],
        [9.9773e-01, 2.2733e-03],
        [9.9971e-01, 2.8932e-04],
        [9.9928e-01, 7.2431e-04],
        [9.9769e-01, 2.3072e-03],
        [9.9918e-01, 8.2351e-04],
        [9.9953e-01, 4.7397e-04],
        [9.9952e-01, 4.8274e-04],
        [9.9929e-01, 7.1471e-04],
        [9.9947e-01, 5.3310e-04],
        [9.9889e-01, 1.1102e-03],
        [9.9866e-01, 1.3397e-03],
        [9.9932e-01, 6.7979e-04],
        [9.9866e-01, 1.3430e-03],
        [9.9927e-01, 7.2744e-04],
        [9.9832e-01, 1.6771e-03],
        [9.9779e-01, 2.2079e-03],
        [9.9885e-01, 1.1510e-03],
        [9.9985e-01, 1.4960e-04],
        [9.9912e-01, 8.8498e-04],
        [9.9960e-01, 4.0042e-04],
        [9.9827e-01, 1.7336e-03],
        [9.9762e-01, 2.3810e-03],
        [9.9901e-01, 9.9140e-04],
        [9.9954e-01, 4.5977e-04],
        [9.9941e-01, 5.8651e-04],
        [9.9954e-01, 4.6395e-04],
        [9.9566e-01, 4.3376e-03],
        [9.9934e-01, 6.6436e-04],
        [9.9910e-01, 9.0080e-04],
        [9.9970e-01, 2.9868e-04],
        [9.9914e-01, 8.6219e-04],
        [9.9911e-01, 8.8570e-04],
        [9.9837e-01, 1.6291e-03],
        [9.9938e-01, 6.1714e-04],
        [9.9957e-01, 4.2622e-04],
        [9.9921e-01, 7.8554e-04],
        [9.9763e-01, 2.3747e-03],
        [9.9945e-01, 5.4911e-04],
        [9.9918e-01, 8.1988e-04],
        [9.9876e-01, 1.2405e-03],
        [9.9948e-01, 5.2389e-04],
        [9.9930e-01, 6.9864e-04],
        [9.9873e-01, 1.2696e-03],
        [9.9963e-01, 3.7101e-04],
        [9.9937e-01, 6.3131e-04],
        [9.9806e-01, 1.9375e-03],
        [9.9783e-01, 2.1701e-03],
        [9.9942e-01, 5.8443e-04],
        [9.9716e-01, 2.8380e-03],
        [9.9962e-01, 3.8469e-04],
        [9.9855e-01, 1.4505e-03],
        [9.9915e-01, 8.4781e-04],
        [9.9714e-01, 2.8574e-03],
        [9.9944e-01, 5.6183e-04],
        [9.9952e-01, 4.7946e-04],
        [9.9935e-01, 6.5100e-04]], grad_fn=<SoftmaxBackward0>)

In [39]:
yhat = list(z.argmax(1))

In [40]:
y_test = list(y_test)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, yhat)

0.859375

#### Dropout

In [42]:
#creating a network with dropout layers
hidden_sizes = [128, 64, 32, 16]

#Build a feed-forward network
model_dropout = nn.Sequential(
    nn.Linear(input_size, hidden_sizes[0]),
    nn.ReLU(),
    nn.Linear(hidden_sizes[0], hidden_sizes[1]),
    torch.nn.Dropout(0.2), #20% Probability
    nn.ReLU(),
    nn.Linear(hidden_sizes[1], hidden_sizes[2]),
    torch.nn.Dropout(0.1), #10%  Probability
    nn.ReLU(),
    nn.Linear(hidden_sizes[2], output_size),
    nn.Softmax(dim=1)
)

print(model_dropout)

Sequential(
  (0): Linear(in_features=12, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): Dropout(p=0.2, inplace=False)
  (4): ReLU()
  (5): Linear(in_features=64, out_features=32, bias=True)
  (6): Dropout(p=0.1, inplace=False)
  (7): ReLU()
  (8): Linear(in_features=32, out_features=2, bias=True)
  (9): Softmax(dim=1)
)

In [56]:
#define the loss
criterion = nn.NLLLoss()

#Optimizers require the parameters to optimize and a learning rate, change the lr
optimizer = optim.SGD(model_dropout.parameters(), lr=0.1)

In [63]:
epochs = 100

for e in range(epochs):
    running_loss = 0
    for step, (batch_x, batch_y) in enumerate(loder):
        #print(f'b_x shape: {b_x.shape}')  # Add this debug line temporarily
        b_x = Variable(batch_x)
        b_y = Variable(batch_y.type(torch.LongTensor))

        #Training pass
        optimizer.zero_grad()

        output = model_dropout(b_x)
        loss = criterion(output, b_y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    else:
        print(f'Training loss: {running_loss/len(X_train)}')

Training loss: -0.009485396909900252
Training loss: -0.012480733214332351
Training loss: -0.013346393229597705
Training loss: -0.013504743692616906
Training loss: -0.013551811934139147
Training loss: -0.013575073870717314
Training loss: -0.013586571117112659
Training loss: -0.013589965473408804
Training loss: -0.013596565658141612
Training loss: -0.013599503343388185
Training loss: -0.013602233500337664
Training loss: -0.013603736710828162
Training loss: -0.013606811401275178
Training loss: -0.013606975683177466
Training loss: -0.013607263448496375
Training loss: -0.013609027808150848
Training loss: -0.013608702080812416
Training loss: -0.013610573915334849
Training loss: -0.013611056580848147
Training loss: -0.013611145599258304
Training loss: -0.013610526822225678
Training loss: -0.013610521071581984
Training loss: -0.01361146747988237
Training loss: -0.013611065906216298
Training loss: -0.013611295737685561
Training loss: -0.01361248790829247
Training loss: -0.013611362880336259
Training loss: -0.013611534156264662
Training loss: -0.013611033345139167
Training loss: -0.013613475659058334
Training loss: -0.013612950679687043
Training loss: -0.013612743773081156
Training loss: -0.013614170437841402
Training loss: -0.01361295965535389
Training loss: -0.01361371372793613
Training loss: -0.0136124897733661
Training loss: -0.01361421667612516
Training loss: -0.01361265300616447
Training loss: -0.0136150257683795
Training loss: -0.013613452501060755
Training loss: -0.013614831101319315
Training loss: -0.013615221717677806
Training loss: -0.013613965279742046
Training loss: -0.013614020377125547
Training loss: -0.013613742714288803
Training loss: -0.013614777907865144
Training loss: -0.013612525093197977
Training loss: -0.013612897563944274
Training loss: -0.013615895864083839
Training loss: -0.013612979316338411
Training loss: -0.013614660097380816
Training loss: -0.013613710969181384
Training loss: -0.013615059767117556
Training loss: -0.013615092755607397
Training loss: -0.013614467683951267
Training loss: -0.01361548348853299
Training loss: -0.013613541402903809
Training loss: -0.013615212003752647
Training loss: -0.01361491025038151
Training loss: -0.013613950164874499
Training loss: -0.013614303635183183
Training loss: -0.013614656367233555
Training loss: -0.013614350339735347
Training loss: -0.01361404380711303
Training loss: -0.013614065216604082
Training loss: -0.01361441410194009
Training loss: -0.013614105432254239
Training loss: -0.0136134675770726
Training loss: -0.013616113766853004
Training loss: -0.013616460320846976
Training loss: -0.013613520615103968
Training loss: -0.013614522897901871
Training loss: -0.013615195800925482
Training loss: -0.013614554526442188
Training loss: -0.013614898477104218
Training loss: -0.013614913009136255
Training loss: -0.013615584435643242
Training loss: -0.013614283702208756
Training loss: -0.013614954507024534
Training loss: -0.01361431027950799
Training loss: -0.013614980190642653
Training loss: -0.013614334991733595
Training loss: -0.013614675872795273
Training loss: -0.013614358849133786
Training loss: -0.013616012392330045
Training loss: -0.01361569494125585
Training loss: -0.013614719974015496
Training loss: -0.013614730270776164
Training loss: -0.013613754992690205
Training loss: -0.013616393294763378
Training loss: -0.01361475999538715
Training loss: -0.013615426176374552
Training loss: -0.013614778607267754
Training loss: -0.013614130416469748
Training loss: -0.013615453219942194
Training loss: -0.013615133010113255
Training loss: -0.013614155672675161
Training loss: -0.013615477893312099
Training loss: -0.013615485819875029
Training loss: -0.013616807768522062

In [65]:
from sklearn.metrics import accuracy_score

X_test_tensor = Tensor(X_test.values)
y_test = Tensor(np.array(y_test))
z = model_dropout(X_test_tensor)

yhat = list(z.argmax(1))
y_test = list(y_test)

print("Accuracy Score of Test Data: ", accuracy_score(y_test, yhat) * 100)

TypeError: new(): data must be a sequence (got builtin_function_or_method)

#### Regularization